### ISSUE TITLE
Swan client directory is not created

### ISSUE THREAD

**Issue by hakimio** [SpoonX/swan-cli#31]
Running `swan new swantest` doesn't create the client directory. 
Output:
```
C:\Users\PC1>swan new swantest
? Where is your project hosted: Github
? Enter a nice description for the project: Swan stack test
? Enter the name of the owner (upstream, e.g. google, spoonx): hakimio

- Setting up project.
Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.


Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.

Done!
- Setting up server and client, this may take a while:
  - Installing server. (1/2)
Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.


Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.

Done!
  - Installing client. (2/2) Error!
Error: Cannot use simple-git on a directory that does not exist.
    at module.exports (C:\Users\PC1\AppData\Roaming\npm\node_modules\swan-cli\node_modules\simple-git\src\index.js:11:15)
    at module.exports (C:\Users\PC1\AppData\Roaming\npm\node_modules\swan-cli\lib\generator\new\new-client.js:12:27)
    at newProject.then.then (C:\Users\PC1\AppData\Roaming\npm\node_modules\swan-cli\lib\generator\new\index.js:64:14)
    at <anonymous>

<3 Created project swantest!
<3 Make sure to verify the existence of the repositories on Github.
```

npm version 5.4.2

**Comment by RWOverdijk** [comment]
I haven't used this for ages, it needs a huge overhaul.

**Comment by hakimio** [comment]
@RWOverdijk any suggestion which example projects I should take a look to start with Aurelia + ORM +Authentication + notification + some UI toolkit (preferrably Material based)?

**Comment by RWOverdijk** [comment]
@hakimio swan-example-client. All this cli lib does is install swan-example-client and swan-example-server.

For a UI toolkit maybe look at [admin-on-rest](https://github.com/marmelab/admin-on-rest). It's react, but I recommend it. It's where I was going with aurelia.

**Comment by hakimio** [comment]
Thanks, I'll take a look at it.
Do you also have some suggestions for Angular 2/4 examples?

**Comment by RWOverdijk** [comment]
Yeah. Don't use it. But that's my opinion.
